In [1]:
import numpy as np
import torch

In [9]:
array=np.load(r"/home/rmedu/Music/RabeyaAkter[SK-092-015]/thesis/Dataset/i3d-features(cvpr23)/span=16_stride=2/001c5ce8-cb49-4677-bd6f-d70d51b7eb17.npy")

In [10]:
print(array)

[[0.         0.13390173 0.0065851  ... 0.16437201 0.         0.03670276]
 [0.         0.13283736 0.00841454 ... 0.16180544 0.         0.02843643]
 [0.         0.1383759  0.01674679 ... 0.15796869 0.         0.04491772]
 ...
 [0.0043533  0.00451147 0.00050278 ... 0.02254036 0.18282852 0.01166988]
 [0.00377377 0.00828078 0.00110407 ... 0.01848504 0.19315948 0.01184052]
 [0.00379239 0.00815957 0.00103514 ... 0.01542715 0.21679793 0.00453026]]


In [11]:
array.shape

(82, 1024)

In [2]:
tensor=torch.load(r"/home/rmedu/Music/RabeyaAkter[SK-092-015]/thesis/Codes/TSPNet_Bangla/i3d-features/span=16_stride=2/0a0c9120-1c35-4341-8115-023446722915.mp4.pt")

In [5]:
tensor[0].shape

torch.Size([1, 1024])

In [6]:
len(tensor)

68

#nslt_2000_065538_0.5147i62

In [1]:
import torch

file_path = '/home/rmedu/Music/RabeyaAkter[SK-092-015]/thesis/Codes/i3d extractor working cvpr23/checkpoints/archive/nslt_2000_065538_0.514762.pt'
model = torch.load(file_path)

In [4]:
for name, param in model.items():
    print(f'Parameter name: {name}')
    print(f'Parameter shape: {param.shape}')
    print('-------------------------')

Parameter name: logits.conv3d.weight
Parameter shape: torch.Size([2000, 1024, 1, 1, 1])
-------------------------
Parameter name: logits.conv3d.bias
Parameter shape: torch.Size([2000])
-------------------------
Parameter name: Conv3d_1a_7x7.conv3d.weight
Parameter shape: torch.Size([64, 3, 7, 7, 7])
-------------------------
Parameter name: Conv3d_1a_7x7.bn.weight
Parameter shape: torch.Size([64])
-------------------------
Parameter name: Conv3d_1a_7x7.bn.bias
Parameter shape: torch.Size([64])
-------------------------
Parameter name: Conv3d_1a_7x7.bn.running_mean
Parameter shape: torch.Size([64])
-------------------------
Parameter name: Conv3d_1a_7x7.bn.running_var
Parameter shape: torch.Size([64])
-------------------------
Parameter name: Conv3d_1a_7x7.bn.num_batches_tracked
Parameter shape: torch.Size([])
-------------------------
Parameter name: Conv3d_2b_1x1.conv3d.weight
Parameter shape: torch.Size([64, 64, 1, 1, 1])
-------------------------
Parameter name: Conv3d_2b_1x1.bn.wei